/* generated by sea-front --emit-c */
#include <stdint.h>
#include <stddef.h>
extern void *memset(void *, int, unsigned long);
extern void *malloc(unsigned long);
extern void  free(void *);
static inline void *_Znwm(unsigned long __sf_n) __attribute__((malloc));
static inline void *_Znwm(unsigned long __sf_n) { return malloc(__sf_n); }
static inline void *_Znam(unsigned long __sf_n) __attribute__((malloc));
static inline void *_Znam(unsigned long __sf_n) { return malloc(__sf_n); }
static inline void _ZdlPv(void *__sf_p) { free(__sf_p); }
static inline void _ZdaPv(void *__sf_p) { free(__sf_p); }
static inline void *_ZnwmPv(unsigned long __sf_unused_0, void *__p) { (void)__sf_unused_0; return __p; }
static inline void *_ZnamPv(unsigned long __sf_unused_0, void *__p) { (void)__sf_unused_0; return __p; }
static inline void _ZdlPvS_(void *__sf_unused_0, void *__sf_unused_1) { (void)__sf_unused_0; (void)__sf_unused_1; }
static inline void _ZdaPvS_(void *__sf_unused_0, void *__sf_unused_1) { (void)__sf_unused_0; (void)__sf_unused_1; }

/* sea-front cleanup protocol — see emit_c.c.
 * The goto-chain destructor cleanup (N4659 §15.4 [class.dtor]/9)
 * emits __SF_cleanup_N labels structurally; not all paths
 * reach every label, triggering -Wunused-label under -Wall. */
#if defined(__GNUC__) || defined(__clang__)
#  pragma GCC diagnostic ignored "-Wunused-label"
#endif
typedef enum {
    __SF_UNWIND_NONE   = 0,
    __SF_UNWIND_RETURN = 1,
    __SF_UNWIND_BREAK  = 2,
    __SF_UNWIND_CONT   = 3,
    __SF_UNWIND_THROW  = 4,
} __SF_unwind_t;
#define __SF_RETURN(v, lbl) do { __SF_retval = (v); __SF_unwind = __SF_UNWIND_RETURN; goto lbl; } while (0)
#define __SF_RETURN_VOID(lbl) do { __SF_unwind = __SF_UNWIND_RETURN; goto lbl; } while (0)
#define __SF_BREAK(lbl) do { __SF_unwind = __SF_UNWIND_BREAK; goto lbl; } while (0)
#define __SF_CONT(lbl) do { __SF_unwind = __SF_UNWIND_CONT; goto lbl; } while (0)
#define __SF_PROLOGUE(ret_type) ret_type __SF_retval = {0}; __SF_unwind_t __SF_unwind = __SF_UNWIND_NONE; (void)__SF_unwind
#define __SF_PROLOGUE_VOID __SF_unwind_t __SF_unwind = __SF_UNWIND_NONE; (void)__SF_unwind
#define __SF_EPILOGUE __SF_epilogue: ; return __SF_retval
#define __SF_EPILOGUE_VOID __SF_epilogue: ; return
#define __SF_CHAIN_ANY(lbl) do { if (__SF_unwind) goto lbl; } while (0)
#define __SF_CHAIN_RETURN(lbl) do { if (__SF_unwind == __SF_UNWIND_RETURN) goto lbl; } while (0)
#define __SF_CHAIN_BREAK(lbl) do { if (__SF_unwind == __SF_UNWIND_BREAK)  goto lbl; } while (0)
#define __SF_CHAIN_CONT(lbl) do { if (__SF_unwind == __SF_UNWIND_CONT)   goto lbl; } while (0)
#define __SF_CHAIN_THROW(lbl) do { if (__sf_exc_state.state == __SF_UNWIND_THROW) goto lbl; } while (0)
struct __sf_type_info {
    const char *name;
    const struct __sf_type_info *parent;
    int n_parents;
    const void *parents;
};
struct __sf_exception_state {
    __SF_unwind_t state;
    void *exc_obj;
    const struct __sf_type_info *exc_type;
    void (*exc_dtor)(void *);
};
#if __STDC_VERSION__ >= 201112L
__attribute__((weak)) _Thread_local struct __sf_exception_state __sf_exc_state;
#elif defined(__GNUC__) || defined(__clang__)
__attribute__((weak)) __thread struct __sf_exception_state __sf_exc_state;
#else
__attribute__((weak)) struct __sf_exception_state __sf_exc_state;
#endif
static const struct __sf_type_info __sf_typeinfo_int = { "int", 0, 0, 0 };
#define __SF_THROW_PRIM(val, ti, lbl) do { __sf_exc_state.exc_obj = (void *)(uintptr_t)(val); __sf_exc_state.exc_type = (ti); __sf_exc_state.exc_dtor = 0; __sf_exc_state.state = __SF_UNWIND_THROW; __SF_unwind = __SF_UNWIND_THROW; goto lbl; } while (0)
#define __SF_THROW_CLASS(p_val, ti, lbl) do { __sf_exc_state.exc_obj = (void *)(p_val); __sf_exc_state.exc_type = (ti); __sf_exc_state.exc_dtor = 0; __sf_exc_state.state = __SF_UNWIND_THROW; __SF_unwind = __SF_UNWIND_THROW; goto lbl; } while (0)
extern void abort(void);
extern void _ZSt9terminatev(void) __attribute__((weak));
static inline void __sf_terminate(void) {
    if (_ZSt9terminatev) _ZSt9terminatev();
    abort();
}
#define __SF_INLINE static inline

struct sf__geom__Vec;

/* C++: struct Vec */
struct sf__geom__Vec {
    int x;
    int y;
};
/* C++: Vec(int a, int b) : x(a), y(b) */
__SF_INLINE void sf__geom__Vec__ctor_p_int_int_pe_(struct sf__geom__Vec *this, int a, int b);
/* C++: int scale(int k)            const */
__SF_INLINE int sf__geom__Vec__scale_p_int_pe__const(const struct sf__geom__Vec *this, int k);
/* C++: int scale(int kx, int ky)   const */
__SF_INLINE int sf__geom__Vec__scale_p_int_int_pe__const(const struct sf__geom__Vec *this, int kx, int ky);
/* C++: int dot(const Vec &o)       const */
__SF_INLINE int sf__geom__Vec__dot_p_const_Vec_ref_pe__const(const struct sf__geom__Vec *this, const struct sf__geom__Vec* o);
/* C++: Vec operator+(const Vec &o) const */
__SF_INLINE struct sf__geom__Vec sf__geom__Vec__plus_p_const_Vec_ref_pe__const(const struct sf__geom__Vec *this, const struct sf__geom__Vec* o);

int main(void);

/* C++: Vec(int a, int b) : x(a), y(b) */
__SF_INLINE void sf__geom__Vec__ctor_p_int_int_pe_(struct sf__geom__Vec *this, int a, int b) {
    this->x = a;
    this->y = b;
}
/* C++: int scale(int k)            const */
__SF_INLINE int sf__geom__Vec__scale_p_int_pe__const(const struct sf__geom__Vec *this, int k) {
    return ((this->x + this->y) * k);
}
/* C++: int scale(int kx, int ky)   const */
__SF_INLINE int sf__geom__Vec__scale_p_int_int_pe__const(const struct sf__geom__Vec *this, int kx, int ky) {
    return ((this->x * kx) + (this->y * ky));
}
/* C++: int dot(const Vec &o)       const */
__SF_INLINE int sf__geom__Vec__dot_p_const_Vec_ref_pe__const(const struct sf__geom__Vec *this, const struct sf__geom__Vec* o) {
    return ((this->x * o->x) + (this->y * o->y));
}
/* C++: Vec operator+(const Vec &o) const */
__SF_INLINE struct sf__geom__Vec sf__geom__Vec__plus_p_const_Vec_ref_pe__const(const struct sf__geom__Vec *this, const struct sf__geom__Vec* o) {
    struct sf__geom__Vec __SF_temp_0;
    sf__geom__Vec__ctor_p_int_int_pe_(&__SF_temp_0, (this->x + o->x), (this->y + o->y));
    return __SF_temp_0;
}

/* C++: int main() */
int main(void) {
    struct sf__geom__Vec a;
    sf__geom__Vec__ctor_p_int_int_pe_(&a, 3, 4);
    struct sf__geom__Vec b;
    sf__geom__Vec__ctor_p_int_int_pe_(&b, 1, 2);
    struct sf__geom__Vec c = sf__geom__Vec__plus_p_const_Vec_ref_pe__const(&a, &(b));
    return (sf__geom__Vec__scale_p_int_int_pe__const(&c, 2, 3) - sf__geom__Vec__dot_p_const_Vec_ref_pe__const(&a, &(b)));
}
