/* generated by sea-front --emit-c */
#include <stdint.h>
#include <stddef.h>

/* sea-front cleanup protocol — see emit_c.c.
 * The goto-chain destructor cleanup (N4659 §15.4 [class.dtor]/9)
 * emits __SF_cleanup_N labels structurally; not all paths
 * reach every label, triggering -Wunused-label under -Wall. */
#if defined(__GNUC__) || defined(__clang__)
#  pragma GCC diagnostic ignored "-Wunused-label"
#endif
typedef enum {
    __SF_UNWIND_NONE   = 0,
    __SF_UNWIND_RETURN = 1,
    __SF_UNWIND_BREAK  = 2,
    __SF_UNWIND_CONT   = 3,
    __SF_UNWIND_THROW  = 4,
} __SF_unwind_t;
#define __SF_RETURN(v, lbl) do { __SF_retval = (v); __SF_unwind = __SF_UNWIND_RETURN; goto lbl; } while (0)
#define __SF_RETURN_VOID(lbl) do { __SF_unwind = __SF_UNWIND_RETURN; goto lbl; } while (0)
#define __SF_BREAK(lbl) do { __SF_unwind = __SF_UNWIND_BREAK; goto lbl; } while (0)
#define __SF_CONT(lbl) do { __SF_unwind = __SF_UNWIND_CONT; goto lbl; } while (0)
#define __SF_PROLOGUE(ret_type) ret_type __SF_retval = {0}; __SF_unwind_t __SF_unwind = __SF_UNWIND_NONE; (void)__SF_unwind
#define __SF_PROLOGUE_VOID __SF_unwind_t __SF_unwind = __SF_UNWIND_NONE; (void)__SF_unwind
#define __SF_EPILOGUE __SF_epilogue: ; return __SF_retval
#define __SF_EPILOGUE_VOID __SF_epilogue: ; return
#define __SF_CHAIN_ANY(lbl) do { if (__SF_unwind) goto lbl; } while (0)
#define __SF_CHAIN_RETURN(lbl) do { if (__SF_unwind == __SF_UNWIND_RETURN) goto lbl; } while (0)
#define __SF_CHAIN_BREAK(lbl) do { if (__SF_unwind == __SF_UNWIND_BREAK)  goto lbl; } while (0)
#define __SF_CHAIN_CONT(lbl) do { if (__SF_unwind == __SF_UNWIND_CONT)   goto lbl; } while (0)
#define __SF_CHAIN_THROW(lbl) do { if (__sf_exc_state.state == __SF_UNWIND_THROW) goto lbl; } while (0)
struct __sf_type_info {
    const char *name;
    const struct __sf_type_info *parent;
    int n_parents;
    const void *parents;
};
struct __sf_exception_state {
    __SF_unwind_t state;
    void *exc_obj;
    const struct __sf_type_info *exc_type;
    void (*exc_dtor)(void *);
};
#if __STDC_VERSION__ >= 201112L
static _Thread_local struct __sf_exception_state __sf_exc_state;
#elif defined(__GNUC__) || defined(__clang__)
static __thread struct __sf_exception_state __sf_exc_state;
#else
static struct __sf_exception_state __sf_exc_state;
#endif
static const struct __sf_type_info __sf_typeinfo_int = { "int", 0, 0, 0 };
#define __SF_THROW_PRIM(val, ti, lbl) do { __sf_exc_state.exc_obj = (void *)(uintptr_t)(val); __sf_exc_state.exc_type = (ti); __sf_exc_state.exc_dtor = 0; __sf_exc_state.state = __SF_UNWIND_THROW; __SF_unwind = __SF_UNWIND_THROW; goto lbl; } while (0)
#define __SF_INLINE static inline

struct sf__Animal;
struct sf__Cat;

/* C++: struct Animal */
struct sf__Animal__vtable;
struct sf__Animal {
    const struct sf__Animal__vtable *__sf_vptr;
    int weight;
};
/* C++: Animal(int w) : weight(w) */
__SF_INLINE void sf__Animal__ctor_p_int_pe_(struct sf__Animal *this, int w);
/* C++: virtual int speak() */
__SF_INLINE int sf__Animal__speak_p_void_pe_(struct sf__Animal *this);

/* C++: struct Cat : Animal */
struct sf__Cat__vtable;
struct sf__Cat {
    struct sf__Animal __sf_base;
};
/* C++: Cat(int w) : Animal(w) */
__SF_INLINE void sf__Cat__ctor_p_int_pe_(struct sf__Cat *this, int w);
/* C++: virtual int speak() */
__SF_INLINE int sf__Cat__speak_p_void_pe_(struct sf__Cat *this);

int describe_p_Animal_ptr_pe_(struct sf__Animal* a);

int main(void);

struct sf__Animal__vtable {
    int (*speak)(struct sf__Animal *);
};
static const struct sf__Animal__vtable sf__Animal__vtable_instance = {
    sf__Animal__speak_p_void_pe_,
};
/* C++: Animal(int w) : weight(w) */
__SF_INLINE void sf__Animal__ctor_p_int_pe_(struct sf__Animal *this, int w) {
    this->__sf_vptr = &sf__Animal__vtable_instance;
    this->weight = w;
}
/* C++: virtual int speak() */
__SF_INLINE int sf__Animal__speak_p_void_pe_(struct sf__Animal *this) {
    return 0;
}

struct sf__Cat__vtable {
    int (*speak)(struct sf__Cat *);
};
static const struct sf__Cat__vtable sf__Cat__vtable_instance = {
    sf__Cat__speak_p_void_pe_,
};
/* C++: Cat(int w) : Animal(w) */
__SF_INLINE void sf__Cat__ctor_p_int_pe_(struct sf__Cat *this, int w) {
    sf__Animal__ctor_p_int_pe_(&this->__sf_base, w);
    ((struct sf__Animal *)this)->__sf_vptr = &sf__Cat__vtable_instance;
}
/* C++: virtual int speak() */
__SF_INLINE int sf__Cat__speak_p_void_pe_(struct sf__Cat *this) {
    return 7;
}

/* C++: int describe(Animal *a) */
int describe_p_Animal_ptr_pe_(struct sf__Animal* a) {
    return (((a)->__sf_vptr->speak(a) * 10) + a->weight);
}

/* C++: int main() */
int main(void) {
        struct sf__Animal a;
    sf__Animal__ctor_p_int_pe_(&a, 3);
        struct sf__Cat c;
    sf__Cat__ctor_p_int_pe_(&c, 4);
    return (describe_p_Animal_ptr_pe_((&a)) + describe_p_Animal_ptr_pe_((&c)));
}
