/* generated by sea-front --emit-c */
#include <stdint.h>
#include <stddef.h>

/* sea-front cleanup protocol — see emit_c.c.
 * The goto-chain destructor cleanup (N4659 §15.4 [class.dtor]/9)
 * emits __SF_cleanup_N labels structurally; not all paths
 * reach every label, triggering -Wunused-label under -Wall. */
#if defined(__GNUC__) || defined(__clang__)
#  pragma GCC diagnostic ignored "-Wunused-label"
#endif
typedef enum {
    __SF_UNWIND_NONE   = 0,
    __SF_UNWIND_RETURN = 1,
    __SF_UNWIND_BREAK  = 2,
    __SF_UNWIND_CONT   = 3,
    __SF_UNWIND_THROW  = 4,
} __SF_unwind_t;
#define __SF_RETURN(v, lbl) do { __SF_retval = (v); __SF_unwind = __SF_UNWIND_RETURN; goto lbl; } while (0)
#define __SF_RETURN_VOID(lbl) do { __SF_unwind = __SF_UNWIND_RETURN; goto lbl; } while (0)
#define __SF_BREAK(lbl) do { __SF_unwind = __SF_UNWIND_BREAK; goto lbl; } while (0)
#define __SF_CONT(lbl) do { __SF_unwind = __SF_UNWIND_CONT; goto lbl; } while (0)
#define __SF_PROLOGUE(ret_type) ret_type __SF_retval = {0}; __SF_unwind_t __SF_unwind = __SF_UNWIND_NONE; (void)__SF_unwind
#define __SF_PROLOGUE_VOID __SF_unwind_t __SF_unwind = __SF_UNWIND_NONE; (void)__SF_unwind
#define __SF_EPILOGUE __SF_epilogue: ; return __SF_retval
#define __SF_EPILOGUE_VOID __SF_epilogue: ; return
#define __SF_CHAIN_ANY(lbl) do { if (__SF_unwind) goto lbl; } while (0)
#define __SF_CHAIN_RETURN(lbl) do { if (__SF_unwind == __SF_UNWIND_RETURN) goto lbl; } while (0)
#define __SF_CHAIN_BREAK(lbl) do { if (__SF_unwind == __SF_UNWIND_BREAK)  goto lbl; } while (0)
#define __SF_CHAIN_CONT(lbl) do { if (__SF_unwind == __SF_UNWIND_CONT)   goto lbl; } while (0)
#define __SF_CHAIN_THROW(lbl) do { if (__sf_exc_state.state == __SF_UNWIND_THROW) goto lbl; } while (0)
struct __sf_type_info {
    const char *name;
    const struct __sf_type_info *parent;
    int n_parents;
    const void *parents;
};
struct __sf_exception_state {
    __SF_unwind_t state;
    void *exc_obj;
    const struct __sf_type_info *exc_type;
    void (*exc_dtor)(void *);
};
#if __STDC_VERSION__ >= 201112L
static _Thread_local struct __sf_exception_state __sf_exc_state;
#elif defined(__GNUC__) || defined(__clang__)
static __thread struct __sf_exception_state __sf_exc_state;
#else
static struct __sf_exception_state __sf_exc_state;
#endif
static const struct __sf_type_info __sf_typeinfo_int = { "int", 0, 0, 0 };
#define __SF_THROW_PRIM(val, ti, lbl) do { __sf_exc_state.exc_obj = (void *)(uintptr_t)(val); __sf_exc_state.exc_type = (ti); __sf_exc_state.exc_dtor = 0; __sf_exc_state.state = __SF_UNWIND_THROW; __SF_unwind = __SF_UNWIND_THROW; goto lbl; } while (0)
#define __SF_INLINE static inline

struct sf__Box_t_char_te_;
struct sf__Box_t_int_te_;

static inline int max_t_int_te__p_int_int_pe_(int a, int b);

/* C++: struct Box */
struct sf__Box_t_char_te_ {
    char val;
};
/* C++: Box(T v) : val(v) */
__SF_INLINE void sf__Box_t_char_te___ctor_p_char_pe_(struct sf__Box_t_char_te_ *this, char v);
/* C++: T get() */
__SF_INLINE char sf__Box_t_char_te___get_p_void_pe_(struct sf__Box_t_char_te_ *this);

/* C++: struct Box */
struct sf__Box_t_int_te_ {
    int val;
};
/* C++: Box(T v) : val(v) */
__SF_INLINE void sf__Box_t_int_te___ctor_p_int_pe_(struct sf__Box_t_int_te_ *this, int v);
/* C++: T get() */
__SF_INLINE int sf__Box_t_int_te___get_p_void_pe_(struct sf__Box_t_int_te_ *this);



int main(void);

/* C++: T max(T a, T b) */
static inline int max_t_int_te__p_int_int_pe_(int a, int b) {
    return ((a > b) ? a : b);
}

/* C++: Box(T v) : val(v) */
__SF_INLINE void sf__Box_t_char_te___ctor_p_char_pe_(struct sf__Box_t_char_te_ *this, char v) {
    this->val = v;
}
/* C++: T get() */
__SF_INLINE char sf__Box_t_char_te___get_p_void_pe_(struct sf__Box_t_char_te_ *this) {
    return this->val;
}

/* C++: Box(T v) : val(v) */
__SF_INLINE void sf__Box_t_int_te___ctor_p_int_pe_(struct sf__Box_t_int_te_ *this, int v) {
    this->val = v;
}
/* C++: T get() */
__SF_INLINE int sf__Box_t_int_te___get_p_void_pe_(struct sf__Box_t_int_te_ *this) {
    return this->val;
}



/* C++: int main() */
int main(void) {
    struct sf__Box_t_int_te_ bi;
    sf__Box_t_int_te___ctor_p_int_pe_(&bi, 40);
    struct sf__Box_t_char_te_ bc;
    sf__Box_t_char_te___ctor_p_char_pe_(&bc, 'A');
    int m1 = max_t_int_te__p_int_int_pe_(sf__Box_t_int_te___get_p_void_pe_(&bi), 30);
    int m2 = max_t_int_te__p_int_int_pe_((int)sf__Box_t_char_te___get_p_void_pe_(&bc), 60);
    return ((m2 - m1) - 24);
}
